---
title: "In-class Ex4: Interactivity & Statistical Analysis"
date: "February 4, 2023"
date-modified: "`r Sys.Date()`"
execute:
  echo: true
  eval: true
  warning: false
---

Loading packages and data

```{r}
pacman::p_load(plotly, DT, patchwork, tidyverse, ggstatsplot, readxl, performance, parameters, see)
exam_data <- read_csv("data/Exam_data.csv")
```

```{r}
plot_ly(data = exam_data, 
        x = ~ENGLISH, 
        y = ~MATHS, 
        color = ~RACE)
```

```{r}
p <- ggplot(data=exam_data, 
            aes(x = MATHS,
                y = ENGLISH)) +
  geom_point(dotsize = 1) +
  coord_cartesian(xlim = c(0,100),
                  ylim = c(0,100))
ggplotly(p)
```

```{r}
ggplot(data=exam_data, 
            aes(x = MATHS,
                y = ENGLISH)) +
  geom_point(dotsize = 1) +
  coord_cartesian(xlim = c(0,100),
                  ylim = c(0,100))
```

```{r}
ggbetweenstats(
  data = exam_data,
  x = GENDER, 
  y = MATHS,
  type = "p",
  messages = FALSE
)
```

```{r}
ggscatterstats(
  data = exam_data,
  x = MATHS,
  y = ENGLISH,
  marginal = TRUE,
  )
```

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls", "data")
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + 
              Weight + Guarantee_Period, data = car_resale)
model
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r}
check_n <- check_normality(model)
plot(check_n)
```

```{r}
my_sum <- exam_data %>%
  group_by(RACE) %>%
  summarise(
    n = n(),
    mean = mean(MATHS),
    sd = sd(MATHS)
    ) %>%
  mutate(se = sd / sqrt(n-1))
knitr::kable(head(my_sum), format = 'html')
```

```{r}
ggplot(my_sum) +
  geom_errorbar(
    aes(x = RACE, 
        ymin = mean-se, 
        ymax = mean+se), 
    width = 0.2, 
    colour = "black", 
    alpha = 0.9, 
    size = 0.5) +
  geom_point(aes
           (x = RACE, 
            y = mean), 
           stat = "identity", 
           color = "red",
           size = 1.5,
           alpha = 1) +
  ggtitle("Standard error of mean 
          maths score by rac")
```
